Repository voideditor/void, pull requests merged in 2024-10, with the labels that each got.

#52 Input box style
  extensions/void/src/sidebar/Sidebar.tsx
  extensions/void/src/sidebar/components/Files.tsx
  extensions/void/src/sidebar/markdown/BlockCode.tsx
  extensions/void/src/sidebar/utils/classNames.ts
  extensions/void/src/sidebar/utils/index.ts
  extensions/void/tailwind.config.js
Labels: enhancement

#53 Persist chat threads history
  extensions/void/.vscode/settings.json
  extensions/void/README.md
  extensions/void/package.json
  extensions/void/src/common/sendLLMMessage.ts
  extensions/void/src/extension.ts
  extensions/void/src/shared_types.ts
  extensions/void/src/sidebar/Sidebar.tsx
  extensions/void/src/sidebar/chatContext.tsx
  extensions/void/src/sidebar/components/SelectedFiles.tsx
  extensions/void/src/sidebar/getVscodeApi.ts
  extensions/void/src/sidebar/index.tsx
  extensions/void/src/sidebar/markdown/BlockCode.tsx
  extensions/void/src/sidebar/utils/classNames.ts
  extensions/void/src/sidebar/utils/index.ts
Labels: enhancement

#101 Refactor and fix diff highlighting
  extensions/void/package-lock.json
  extensions/void/package.json
  extensions/void/src/ApprovalCodeLensProvider.ts
  extensions/void/src/DisplayChangesProvider.ts
  extensions/void/src/extension.ts
  extensions/void/src/findDiffs.ts
  extensions/void/src/getDiffedLines.ts
  extensions/void/src/shared_types.ts
  extensions/void/src/sidebar/Sidebar.tsx
  extensions/void/src/sidebar/getVscodeApi.ts
  extensions/void/src/sidebar/markdown/BlockCode.tsx
Labels: high priority 🚀

#77 Fix: Add Syntax Highlighting to Sidebar Code Snippets
  extensions/void/package-lock.json
  extensions/void/package.json
Labels: high priority 🚀

#87 Added displaying error messages in UI
  extensions/void/src/common/sendLLMMessage.ts
  extensions/void/src/sidebar/Sidebar.tsx
Labels: high priority 🚀

#110 Settings update
  extensions/void/package-lock.json
  extensions/void/package.json
  extensions/void/src/DisplayChangesProvider.ts
  extensions/void/src/SidebarWebviewProvider.ts
  extensions/void/src/common/sendLLMMessage.ts
  extensions/void/src/extension.ts
  extensions/void/src/shared_types.ts
  extensions/void/src/sidebar/Sidebar.tsx
  extensions/void/src/sidebar/SidebarChat.tsx
  extensions/void/src/sidebar/SidebarSettings.tsx
  extensions/void/src/sidebar/SidebarThreadSelector.tsx
  extensions/void/src/sidebar/contextForConfig.tsx
  extensions/void/src/sidebar/contextForThreads.tsx
  extensions/void/src/sidebar/getVscodeApi.ts
  extensions/void/src/sidebar/index.tsx
  extensions/void/src/sidebar/styles.css
  extensions/void/tailwind.config.js
Labels: new feature

#113 Misc Improvements
  extensions/void/package-lock.json
  extensions/void/package.json
  extensions/void/src/SidebarWebviewProvider.ts
  extensions/void/src/common/shared_types.ts
  extensions/void/src/extension.ts
  extensions/void/src/sidebar/CtrlK.tsx
  extensions/void/src/sidebar/Sidebar.tsx
  extensions/void/src/sidebar/SidebarChat.tsx
  extensions/void/src/sidebar/SidebarSettings.tsx
  extensions/void/src/sidebar/SidebarThreadSelector.tsx
  extensions/void/src/sidebar/components/SelectedFiles.tsx
  extensions/void/src/sidebar/contextForConfig.tsx
  extensions/void/src/sidebar/contextForThreads.tsx
  extensions/void/src/sidebar/getVscodeApi.ts
  extensions/void/src/sidebar/index.tsx
  extensions/void/src/sidebar/markdown/BlockCode.tsx
  extensions/void/src/sidebar/markdown/MarkdownRender.tsx
  extensions/void/src/sidebar/metrics/posthog.tsx
Labels: new feature

#134 Gemini added #new feature
  extensions/void/package-lock.json
  extensions/void/package.json
  extensions/void/src/common/sendLLMMessage.ts
  extensions/void/src/webviews/common/contextForConfig.tsx
Labels: integration request
